#!/bin/bash

## Author : OSITO326
## Github : @OSITO326
#
## Rofi   : Launcher (Modi Drun, Run, File Browser, Window)

dir="$HOME/.config/rofi/theme/launcher"
theme='style'

## Run
rofi \
  -modi "clipboard:greenclip print" \
  -show clipboard -run-command '{cmd}' \
  -theme ${dir}/${theme}.rasi
