#!/bin/bash

## Author : OSITO326
## Github : @OSITO326
#
## Rofi   : Launcher (Modi Drun, Run, File Browser, Window)
#

dir="$HOME/.config/rofi/theme/launcher"
theme='style'

## Run
rofi \
    -modi emoji -show emoji -emoji-format '{emoji} <span weight="bold">{name}</span>[ <span size="small">({keywords})</span>]' \
    -theme ${dir}/${theme}.rasi
